### ISSUE TITLE
TrNode is a god object

### ISSUE THREAD

**Issue by nomel7** [sanity/tahrir#60]
`TrNode` is a god object: https://en.wikipedia.org/wiki/God_object

This makes it difficult to test downstream dependencies as we have to inject a TrNode every time we want to access things like the `incomingMbHandler`. We should refactor TrNode and its properties so we don't have to create a TrNode for every unit test.

**Comment by nomel7** [comment]
Found a workaround.

**Comment by sanity** [comment]
I designed this before I learned about Dependency Injection frameworks :)  TrNode definitely needs a refactor.  What was your workaround?

**Comment by nomel7** [comment]
I've added Spring Boot (I noticed there was Guice too but didn't want the hassle of trying to mix Spring Boot with Guice), so TrNode is created as a bean and injected at the moment. It could still do with a refactor though alright but it's probably not a priority for the moment.

I have it working as a bean on my repo (https://github.com/nomel7/tahrir) if you want to check it out.

**Comment by sanity** [comment]
Yes, we experimented with Guice as a dependency injection framework.  I'm not so familiar with Spring Boot, but if I understand correctly it is also a dependency injection framework, among other things, so it definitely doesn't make sense to have two DI frameworks :)

If you're more comfortable with Sprint Boot then it probably makes sense to go with that.

**Comment by nomel7** [comment]
Yeah, sounds good. When things are a bit more stable I will look into removing Guice and replacing it with Spring. I think Guice is probably a little nicer as a standalone framework but Spring DI comes with Spring Boot. I had a look at the Jar sizes and it looks like Spring Boot in total is around the same size as Guice, so that's a plus as well.
