### ISSUE TITLE
What are the allowed characters for a username?

### ISSUE THREAD

**Issue by nomel7** [sanity/tahrir#61]
I couldn't find in the source what are allowed characters are for a username. Is this something we have already settled on?

If not, I would like to suggest that we only allow alphanumeric as this would simplify the parsing on a microblog on the client side. For example if a user is called `@nomel7! ` and the message they were sending was `This is a message for @nomel7!`, it is difficult to know whether the '!' was part of the message or part of the username. If we only allow alphanumeric then I don't think this would be an issue.

**Comment by nomel7** [comment]
It looks like this is already in the server side code as limited to alphanumeric. There might be a bug which was causing the issue with the client side code I was working on.

**Comment by sanity** [comment]
That sounds reasonable, here is an article on Twitter's rules for usernames (note: it's from 2009 so might be outdated, but probably not):

http://kagan.mactane.org/blog/2009/09/22/what-characters-are-allowed-in-twitter-usernames/comment-page-1/

Here is some info on what Github allows and why:
https://www.quora.com/Why-doesnt-GitHub-allow-underscores-or-spaces-in-repository-names
