### ISSUE TITLE
XML format for mentions

### ISSUE THREAD

**Issue by nomel7** [sanity/tahrir#62]
There is a bug somewhere in the code regarding microblogs that contain a mention causing an index out of bounds exception for a microblog that contains a mention. Currently, according to a comment in the source, a message with a mention has the inner tag `<mtn>`. Does this mean that a mention inside a `<txt>` would look like `<mtn>@nomel7</mtn>` or `<mtn>nomel7</mtn>` for the user `@nomel7`. On that note, is the mention tag necessary at all if all mentions are preceded by `@`? Is there a reason why we need the `<mtn>` tag?

**Comment by nomel7** [comment]
Looking into this further it appears the `<mtn>` is necessary for encoding public key information with the mention. But what happens if the user does not have the user in their identity store? Should we treat the mention as plain text then?

**Comment by sanity** [comment]
Who wrote that code, was it @ravisvi ?

**Comment by nomel7** [comment]
Yes, I believe it was @ravisvi. There's another format in `TrConstants` that seems to make more sense to me:

```
/**
	 * Records constants to do with the microblog XML format.
	 *
	 * Example: <mb>
	 *     			<txt>This is a microblog with a mention </txt>
	 *     			<mtn alias="name">public key encoded in base 64</mtn>
	 * 			</mb>
	 */
```

**Comment by sanity** [comment]
Yeah, I think it's tricky doing signatures in XML because XML isn't whitespace sensitive, but a signature definitely will be.

Regarding mentions, I think yes - if we don't know a user then it should be treated as plaintext, or perhaps not permitted (as it could be confusing for users as to why some mentions work and others don't).

Nicknames in Tahrir are mostly "local" to a user's address book (although users can have "preferred" nicknames).  So, I might call myself "sanity", but you might choose to refer to me as @finbarmacintosh if you want to.  From your perspective in Tahrir that's who I'll be.

**Comment by ravisvi** [comment]
I'll look into this.

**Comment by ravisvi** [comment]
Hi, I haven't been able to look into this yet. Should be able to work on it
in a weeks time.

**Comment by nomel7** [comment]
Working on it now in my branch. Do we want mention elements embedded in text elements? Here are two examples, from the plain text 

> Hello, world! This is a very simple microblog!@user1337

```
<?xml version="1.0"?>
<bm><txt lang="en">Hello, world! This is a very simple microblog!</txt><mtn alias="user1337">MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpZLxYQFwCOYAUjlNYZDXNTEY+rPSnN8KNoP7bYdNUchjjmIWrFnWKHaP1FBAKKgskMZrsjTjdcBSB4ZcHKvVcAc2sxDWhht4dFvRKcBuhdHJkylp76VbmWzYTJHfGo5XxSzOZRhRtJd85aYkWFY5FpIYgGSXk3h4Wul1cXmeiEJG4ia03QalT4THx+2ISLktni9YDkjm9ThOYH8VAMUmd6FT7JwOC6doSkreqYrFQB1HH0JXb0Vyym8YfWDYVJbXKDY49V9G8MJhaRczfk8+t3GoaxT7mQnso1EaKXQMw2ORimyhWe5svPGeBpP4nc+oDRxeWjnZCP9SpHwemzrDwIDAQAB</mtn></bm>
```

```
<?xml version="1.0"?>
<bm><txt lang="en">Hello, world! This is a very simple microblog!<mtn alias="user1337">MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjpZLxYQFwCOYAUjlNYZDXNTEY+rPSnN8KNoP7bYdNUchjjmIWrFnWKHaP1FBAKKgskMZrsjTjdcBSB4ZcHKvVcAc2sxDWhht4dFvRKcBuhdHJkylp76VbmWzYTJHfGo5XxSzOZRhRtJd85aYkWFY5FpIYgGSXk3h4Wul1cXmeiEJG4ia03QalT4THx+2ISLktni9YDkjm9ThOYH8VAMUmd6FT7JwOC6doSkreqYrFQB1HH0JXb0Vyym8YfWDYVJbXKDY49V9G8MJhaRczfk8+t3GoaxT7mQnso1EaKXQMw2ORimyhWe5svPGeBpP4nc+oDRxeWjnZCP9SpHwemzrDwIDAQAB</mtn></txt></bm>

```

Option 1 or 2? I was thinking option 1. What are your thoughts @sanity

**Comment by sanity** [comment]
I think B might be more "markuppy", since the mention is part of the <txt>.

**Comment by nomel7** [comment]
Yeah, I guess the only reason I was thinking otherwise was the length of markup A. I'll go with B for the moment and it should be easier to implement and everything.

**Comment by nomel7** [comment]
Here is my fix on my branch. I won't bother merging it back in with the main branch as I've changed and added dependencies.

https://github.com/k-don/tahrir/commit/36755228b7e04f99b4f4f429a2bd30aba1fe59a7
